version: 2.1

orbs:
  aws-s3: circleci/aws-s3@3.0.0

executors:
  my-executor:
    docker:
      - image: cimg/node:16.10.0
    working_directory: ~/repo
    resource_class: large
  my-test-executor:
    docker:
      - image: cimg/node:16.10.0
    working_directory: ~/repo
    resource_class: large
  terra:
    docker:
      - image: hashicorp/terraform:light
    working_directory: ~/repo
    resource_class: large

jobs:
  test:
    executor: my-test-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - ui/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn lint
      - run:
          command:  yarn test
          no_output_timeout: 15m
      - persist_to_workspace:
          root: .
          paths:
            - .

  build_deploy_dev:
    executor: my-executor
    steps:
      - attach_workspace:
          at: .
      - run: yarn build-dev
      - aws-s3/sync:
          from: ui/build
          to: "s3://admin-portal-dev-uk.techomc.com" ## NEEDS2BE  s3://admin-portal-dev-uk.techomc.com
          arguments: |
            --delete \
            --acl public-read \
            --cache-control "max-age=86400"

  build_deploy_stg:
    executor: my-executor
    steps:
      - attach_workspace:
          at: .
      - run: yarn build-staging
      - aws-s3/sync:
          from: ui/build
          to: "s3://admin-portal-staging-uk.techomc.com" ## NEEDS2BE  s3://admin-portal-stg-uk.techomc.com
          arguments: |
            --delete \
            --acl public-read \
            --cache-control "max-age=86400"

  build_deploy_prod:
    executor: my-executor
    steps:
      - attach_workspace:
          at: .
      - run: yarn build-prod
      - aws-s3/sync:
          from: ui/build
          to: "s3://admin-portal.uk.techomc.com" ## NEEDS2BE  s3://admin-portal.uk.techomc.com  MAYBE BETTER AS s3://admin-portal-uk.techomc.com UPDATE LATER
          arguments: |
            --delete \
            --acl public-read \
            --cache-control "max-age=86400"

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - test
      - build_deploy_dev:
          requires:
            - test
          filters:
            branches:
              only:
                - develop
      - build_deploy_stg:
          requires:
            - test
          filters:
            branches:
              only:
                - main
      - build_deploy_prod:
          requires:
            - build_deploy_stg
          filters:
            branches:
              only:
                - main


