version: 2.1

orbs:
  aws-s3: circleci/aws-s3@3.0.0

executors:
  my-executor:
    docker:
      - image: cimg/node:16.10.0
    working_directory: ~/repo
    resource_class: large
  my-test-executor:
    docker:
      - image: cimg/node:16.10.0
    working_directory: ~/repo
    resource_class: large
  terra:
    docker:
      - image: hashicorp/terraform:light
    working_directory: ~/repo
    resource_class: large

jobs:
  build_dev:
    executor: my-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - ui/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn lint
      - run: yarn build-dev
#     - run:
#         command: yarn test
#         no_output_timeout: 15m
      - persist_to_workspace:
          root: .
          paths:
            - .
#           - ui/build
  test_dev:
    executor: my-test-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          command:  yarn test
          no_output_timeout: 15m
  s3_deploy_dev:
    executor: my-executor
    steps:
      - attach_workspace:
          at: .
      - aws-s3/sync:
          from: ui/build
          to: "s3://admin-portal-dev-uk.techomc.com" ## NEEDS2BE  s3://admin-portal-dev-uk.techomc.com
          arguments: |
            --delete \
            --acl public-read \
            --cache-control "max-age=86400"

  build_stg:
    executor: my-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - ui/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn lint
      - run: yarn build-staging
#     - run:
#         command: yarn test
#         no_output_timeout: 15m
      - persist_to_workspace:
          root: .
          paths:
            - .
#           - ui/build
  test_stg:
    executor: my-test-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          command:  yarn test
          no_output_timeout: 15m
  s3_deploy_stg:
    executor: my-executor
    steps:
      - attach_workspace:
          at: .
      - aws-s3/sync:
          from: ui/build
          to: "s3://admin-portal-stg-uk.techomc.com" ## NEEDS2BE  s3://admin-portal-stg-uk.techomc.com
          arguments: |
            --delete \
            --acl public-read \
            --cache-control "max-age=86400"

  build_prod:
    executor: my-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - ui/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn lint
      - run: yarn build-prod
#     - run:
#         command: yarn test
#         no_output_timeout: 15m
      - persist_to_workspace:
          root: .
          paths:
            - .
#           - ui/build
  test_prod:
    executor: my-test-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          command:  yarn test
          no_output_timeout: 15m
  s3_deploy_prod:
    executor: my-executor
    steps:
      - attach_workspace:
          at: .
      - aws-s3/sync:
          from: ui/build
          to: "s3://admin-portal-uk.techomc.com" ## NEEDS2BE  s3://admin-portal-uk.techomc.com
          arguments: |
            --delete \
            --acl public-read \
            --cache-control "max-age=86400"

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build_dev:
          filters:
            branches:
              ignore:
                - main
                - prod
      - test_dev:
          requires:
            - build_dev
          filters:
            branches:
              ignore:
                - main
                - prod
      - s3_deploy_dev:
          requires:
            - test_dev
          filters:
            branches:
              only:
                - develop
                - feat/dev_circleci_config
      - build_stg:
          filters:
            branches:
              only:
                - main
      - test_stg:
          requires:
            - build_stg
          filters:
            branches:
              only:
                - main
      - s3_deploy_stg:
          requires:
            - test_stg
          filters:
            branches:
              only:
                - main
      - build_prod:
          filters:
            branches:
              only:
                - prod
      - test_prod:
          requires:
            - build_prod
          filters:
            branches:
              only:
                - prod
      - s3_deploy_prod:
          requires:
            - test_prod
          filters:
            branches:
              only:
                - prod
