import { InvestmentForm } from "./models";

export const MIN_INITIAL_INVESTMENT_AMOUNT = 20_000;
export const MIN_MONTHLY_INVESTMENT_AMOUNT = 0;

export const InvestmentQaNames = {
  UK_INVESTMENT_ADVICE_V1: "UK_INVESTMENT_ADVICE_V1",
} as const;

export const INVESTMENT_ACCOUNT_TYPES_SHORT = {
  LISA: "LISA",
  ISA: "ISA",
  GIA: "GIA",
} as const;

export const INVESTMENT_ACCOUNT_TYPES = {
  LISA: "Lifetime ISA",
  ISA: "Stocks & shares ISA",
  GIA: "General Investment Account",
} as const;

export const INVESTMENT_ACCOUNT_PROVIDERS = {
  CURRENT: "Current",
  OMC: "OMC",
  OTHER: "Other",
} as const;

export const PORTFOLIO_NAMES = {
  PARMENION_V1_PORTFOLIO_1: "PARMENION_V1_PORTFOLIO_1",
  PARMENION_V1_PORTFOLIO_2: "PARMENION_V1_PORTFOLIO_2",
  PARMENION_V1_PORTFOLIO_3: "PARMENION_V1_PORTFOLIO_3",
  PARMENION_V1_PORTFOLIO_4: "PARMENION_V1_PORTFOLIO_4",
  PARMENION_V1_PORTFOLIO_5: "PARMENION_V1_PORTFOLIO_5",
  PARMENION_V1_PORTFOLIO_6: "PARMENION_V1_PORTFOLIO_6",
  PARMENION_V1_PORTFOLIO_7: "PARMENION_V1_PORTFOLIO_7",
  PARMENION_V1_PORTFOLIO_8: "PARMENION_V1_PORTFOLIO_8",
  PARMENION_V1_PORTFOLIO_9: "PARMENION_V1_PORTFOLIO_9",
  PARMENION_V1_PORTFOLIO_10: "PARMENION_V1_PORTFOLIO_10",
} as const;

export const INVESTMENT_HUB_FORM_KEYNAMES: (keyof Pick<
  InvestmentForm,
  | "CLIENT_HAS_PLAN_TARGET_EMERGENCY_FUND"
  | "CLIENT_HAS_NO_DEBTS"
  | "UK_INVESTMENT_ADVICE_GOALS_CLIENT_CONFIRMATION"
  | "UK_INVESTMENT_ADVICE_CLIENT_HAS_SUFFICIENT_PROTECTION"
  | "UK_INVESTMENT_ADVICE_CLIENT_MORE_PENSION_CONTRIBUTIONS_FUTURE_CONFIRMATION"
  | "UK_INVESTMENT_ADVICE_CLIENT_PAST_INVESTMENTS_NO_ADVICE_CONFIRMATION"
>)[] = [
  "CLIENT_HAS_PLAN_TARGET_EMERGENCY_FUND",
  "CLIENT_HAS_NO_DEBTS",
  "UK_INVESTMENT_ADVICE_GOALS_CLIENT_CONFIRMATION",
  "UK_INVESTMENT_ADVICE_CLIENT_HAS_SUFFICIENT_PROTECTION",
  "UK_INVESTMENT_ADVICE_CLIENT_MORE_PENSION_CONTRIBUTIONS_FUTURE_CONFIRMATION",
  "UK_INVESTMENT_ADVICE_CLIENT_PAST_INVESTMENTS_NO_ADVICE_CONFIRMATION",
];

/**
 * The number of future withdrawals to display on the Portfolio Suggestions page.
 */
export const NUM_FUTURE_WITHDRAWALS_DISPLAYED = 3 as const;
